/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Logica.Producto;
import ListasAux.ListaEnlazada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gianx
 */
public class Actualizar_Stock extends javax.swing.JInternalFrame {

    int filas;

    /**
     * Creates new form frm_stockproducto
     */
    public Actualizar_Stock() throws Exception {
        initComponents();
        listarProducto();
    }

    private void listar() throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        ListaEnlazada LP;

        modelo.addColumn("ID Prod.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoria");
        modelo.addColumn("T. Unidad");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");

        Object datos[][] = new Object[1][6];

        LP = Producto.consultarTodo();

        for (int i = 0; i < LP.tamaño(); i++) {
            Producto objCliente = (Producto) LP.Buscar(i);
            datos[0][0] = objCliente.getCodProducto();
            datos[0][1] = objCliente.getNombre();
            datos[0][2] = objCliente.getCategoria();
            datos[0][3] = objCliente.getUnidad();
            datos[0][4] = objCliente.getCantidad();
            datos[0][5] = objCliente.getPrecio();

            modelo.addRow(datos[0]);
        }

        table.setModel(modelo);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    public void listarProducto() throws Exception {
        DefaultTableModel modelo = new DefaultTableModel();
        ListaEnlazada LP;

        modelo.addColumn("ID Prod.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoria");
        modelo.addColumn("T. Unidad");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");

        Object datos[][] = new Object[1][6];

        LP = Producto.consultarTodo();

        for (int i = 0; i < LP.tamaño(); i++) {
            Producto objCliente = (Producto) LP.Buscar(i);
            datos[0][0] = objCliente.getCodProducto();
            datos[0][1] = objCliente.getNombre();
            datos[0][2] = objCliente.getCategoria();
            datos[0][3] = objCliente.getUnidad();
            datos[0][4] = objCliente.getCantidad();
            datos[0][5] = objCliente.getPrecio();

            modelo.addRow(datos[0]);
        }

        table.setModel(modelo);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbloperacion = new javax.swing.JLabel();
        cbotipo = new javax.swing.JComboBox();
        txtcantidad = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblcantidadtotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblcantidadactual = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Actualizar Stock");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("Actualizacion de stock");

        lbloperacion.setText("Cantidad Actual :");

        cbotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingreso", "Salida" }));
        cbotipo.setSelectedIndex(-1);

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        lblMonto.setText("Cantidad :");

        jLabel1.setText("Cantidad Total :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Actualizacion :");

        jButton2.setText("Actualiza Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lbloperacion))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblMonto))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcantidadtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcantidadactual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbloperacion)
                    .addComponent(lblcantidadactual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMonto))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addComponent(lblcantidadtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Registrar_Producto pro;
        try {
            pro = new Registrar_Producto();
            Frm_Principal.contenedor.add(pro);
            pro.setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(Registrar_Producto.class.getName()).log(Level.SEVERE, null, ex);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selection = table.getSelectedRow();

        lblcantidadactual.setText(table.getValueAt(selection, 4).toString());

        filas = selection;
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ListaEnlazada lista = Producto.consultarTodo();
            int posCta = table.getSelectedRow();
            String tipo = cbotipo.getSelectedItem().toString();
            if (posCta == -1) //Si no selecciono una cuenta
            {
                JOptionPane.showMessageDialog(this, "Seleccione un Producto", "MENSAJE DE SISTEMA", JOptionPane.ERROR_MESSAGE);
            } else {
                Producto objPro = (Producto) lista.Buscar(posCta);
                if (tipo.equalsIgnoreCase("Ingreso")) {
                    int nueva = Integer.parseInt(lblcantidadactual.getText()) + Integer.parseInt(txtcantidad.getText());
                    objPro.setCantidad(nueva);
                    lblcantidadtotal.setText(String.valueOf(nueva));
                    lblcantidadactual.setText("");            
                    txtcantidad.setText("");
                    cbotipo.setSelectedIndex(-1);
                } else if (tipo.equalsIgnoreCase("Salida")) {
                    if (Integer.parseInt(lblcantidadactual.getText()) >= Integer.parseInt(txtcantidad.getText())) {
                        int nueva = Integer.parseInt(lblcantidadactual.getText()) - Integer.parseInt(txtcantidad.getText());
                        objPro.setCantidad(nueva);
                        lblcantidadtotal.setText(String.valueOf(nueva));
                        lblcantidadactual.setText("");
                        txtcantidad.setText("");
                        cbotipo.setSelectedIndex(-1);
                    }else {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente", "MENSAJE DE SISTEMA", JOptionPane.ERROR_MESSAGE);
                }
                }

                listar();

            }
        } catch (Exception ex) {
            Logger.getLogger(Registrar_Producto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbotipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblcantidadactual;
    private javax.swing.JLabel lblcantidadtotal;
    private javax.swing.JLabel lbloperacion;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
