/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Logica.Compra;
import Capa_Logica.Proveedor;
import Capa_Logica.clsExportarExcel;
import ListasAux.ListaEnlazada;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Gianx
 */
public class frm_Report_Compra extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Report_Compra
     */
    clsExportarExcel obj;
    public frm_Report_Compra(){
        initComponents();
        consultar();
    }
    
    void consultar(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("FECHA");
        model.addColumn("RUC");
        model.addColumn("RAZON SOCIAL");
        model.addColumn("CODIGO COMPRA");
        model.addColumn("TOTAL");
        
        ListaEnlazada datos;
        
        try {
            datos = Compra.consultarTodo();
        
        
        
        Object Dato[] = new Object [5];
        
        for (int i = 0; i < datos.tamaño(); i++) {
            Compra c = (Compra) datos.Buscar(i);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
            Dato[0] = formato.format(c.getFecha());
            Dato[1] = c.getRucProv();
            
            ListaEnlazada pro = Proveedor.BuscarRucProveedor(c.getRucProv());
            for (int j = 0; j < pro.tamaño(); j++) {
                Proveedor p = (Proveedor)pro.Buscar(j);
                Dato[2] = p.getNombre();
            }
            Dato[3] = c.getCodCompra();
            Dato[4] = c.getTotalCompra();
            model.addRow(Dato);
        }
        
        tblDatos.setModel(model);
        
         } catch (Exception ex) {
            Logger.getLogger(frm_Report_Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        jLabel2.setText("Seleccione una compra, para observar el detalle:");

        jLabel1.setText("REPORTE DE COMPRAS");

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iconfinder_119_Excel_logo_logos_4373169.png"))); // NOI18N
        btnExportar.setText("EXPORTAR EXCEL");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        jButton1.setText("VER GRÁFICO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82)
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnExportar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        int fila = tblDatos.getSelectedRow();
        if (fila<0) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {
             String id = tblDatos.getValueAt(fila, 3).toString();            
             String fecha = tblDatos.getValueAt(fila, 0).toString();            
            int valor = JOptionPane.showConfirmDialog(this, "Desea Ver Detalle de Compra","",JOptionPane.YES_NO_OPTION);
            
            if (valor==JOptionPane.YES_OPTION) {
                
                frm_Detalle_Compra frm = new frm_Detalle_Compra();
                Frm_Principal.contenedor.add(frm);  
                frm.setVisible(true);
                frm_Detalle_Compra.lblCodigo.setText(id);
                frm_Detalle_Compra.lblFecha.setText(fecha);
                
                
                
                
            } 
            else{
                System.out.println(id);
            }
        }
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        
            
        try {
            obj = new clsExportarExcel();
            obj.exportarExcel(tblDatos);
        } catch (IOException ex) {
            Logger.getLogger(frm_Report_Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnExportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ListaEnlazada dat = Proveedor.CompraProv();
        DefaultTableModel model = new DefaultTableModel();
     DefaultCategoryDataset ds= new DefaultCategoryDataset();
        model.addColumn("ruc");
        model.addColumn("monto");
        float suma = 0;
         Object Dato[] = new Object [2];
         
        for (int i = 0; i < dat.tamaño(); i++) {
            Compra d = (Compra)dat.Buscar(i);
            Dato[0] = d.getRucProv();
            Dato[1] = d.getTotalCompra();
            
                
            model.addRow(Dato);
            ds.setValue(Float.parseFloat(Dato[1].toString()), String.valueOf(Dato[0]), String.valueOf(Dato[0]));
        }
        
        
               
        
        
        JFreeChart tot = ChartFactory.createBarChart("REPORTE DE COMPRAS", "PROVEEDOR", "MONTO", ds,PlotOrientation.VERTICAL, true, true, false);
        ChartFrame f= new ChartFrame("REPORTE", tot);
       //contenedor1.add(f);
        f.setSize(750,600);
        
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        
        
        
     

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExportar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
