/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.Lista_DetalleVenta;
import Capa_Datos.Lista_Clientes;
import Capa_Datos.Lista_Compras;
import Capa_Datos.Lista_DetallesCompra;
import Capa_Datos.Lista_Productos;
import Capa_Datos.Lista_Proveedores;
import Capa_Datos.Lista_Vendedores;
import Capa_Datos.Lista_Ventas;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import utils.Alternos;

/**
 *
 * @author Gianx
 */
public class Frm_Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        initComponents();
        this.setTitle("--SISTEMA DE VENTAS--");
        this.setExtendedState(MAXIMIZED_BOTH);
     setIconImage (new ImageIcon(getClass().getResource("/imagenes/carro.jpg")).getImage());
     loadLists();
    }
    private void loadLists(){
        Lista_DetalleVenta.obtainLista();
        Lista_Clientes.obtainLista();
        Lista_Compras.obtainLista();
        Lista_DetallesCompra.obtainLista();
        Lista_Productos.obtainLista();
        Lista_Proveedores.obtainLista();
        Lista_Vendedores.obtainLista();
        Lista_Ventas.obtainLista();
        Alternos.message("El sistema ha cargado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProducto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();
        menuProveedor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuVenta = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenuItem();
        menureporte = new javax.swing.JMenu();
        mnuBuscarProvPorMesyAnio = new javax.swing.JMenuItem();
        mnuMayorPrecio = new javax.swing.JMenuItem();
        mnuPorcentajeClientesActivos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        coincidencias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas - Variaditos");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        contenedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/variados (3).png"))); // NOI18N
        contenedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contenedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jMenu1.setText("Mantenimiento");

        menuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zanahoria.png"))); // NOI18N
        menuProducto.setText("Producto");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        jMenu1.add(menuProducto);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chico.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCliente);

        menuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        menuVendedor.setText("Vendedor");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuVendedor);

        menuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        menuProveedor.setText("Proveedor");
        menuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuProveedor);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnet-de-identidad.png"))); // NOI18N
        jMenuItem2.setText("Usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda.png"))); // NOI18N
        jMenu2.setText("Operaciones");

        menuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/supermercado.png"))); // NOI18N
        menuVenta.setText("Vender ");
        menuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuVenta);

        menuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carretilla (2).png"))); // NOI18N
        menuCompra.setText("Compra");
        menuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraActionPerformed(evt);
            }
        });
        jMenu2.add(menuCompra);

        jMenuBar1.add(jMenu2);

        menureporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        menureporte.setText("Reportes");

        mnuBuscarProvPorMesyAnio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        mnuBuscarProvPorMesyAnio.setText("Buscar Proveedores por mes y año");
        mnuBuscarProvPorMesyAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarProvPorMesyAnioActionPerformed(evt);
            }
        });
        menureporte.add(mnuBuscarProvPorMesyAnio);

        mnuMayorPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        mnuMayorPrecio.setText("Productos de Mayor Precio");
        mnuMayorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMayorPrecioActionPerformed(evt);
            }
        });
        menureporte.add(mnuMayorPrecio);

        mnuPorcentajeClientesActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        mnuPorcentajeClientesActivos.setText("Cantidad de clientes de cada departamento");
        mnuPorcentajeClientesActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPorcentajeClientesActivosActionPerformed(evt);
            }
        });
        menureporte.add(mnuPorcentajeClientesActivos);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        jMenuItem4.setText("Mostrar productos por estado y por categorias");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menureporte.add(jMenuItem4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        jMenuItem6.setText("Dado la vigencia y el sexo, mostrar el/los vendedores con la mayor edad");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menureporte.add(jMenuItem6);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        jMenuItem5.setText("Reporte de Compras");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menureporte.add(jMenuItem5);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        jMenuItem7.setText("Reporte de Ventas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menureporte.add(jMenuItem7);

        coincidencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        coincidencias.setText("Reporte de coincidencias ");
        coincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coincidenciasActionPerformed(evt);
            }
        });
        menureporte.add(coincidencias);

        jMenuBar1.add(menureporte);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acerca-de.png"))); // NOI18N
        jMenu4.setText("Acerca de");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reajustar.png"))); // NOI18N
        jMenuItem3.setText("Acerca de mi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/poder.png"))); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrar.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void usuario(){
        menureporte.setVisible(false);
    }
    public void frmactu(java.awt.event.ActionEvent evt) {                                           
        Actualizar_Stock obj = null;
        try {
            obj = new Actualizar_Stock();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
       contenedor.add(obj).setVisible(true);
    }   
    private void menuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaActionPerformed
        Registrar_Venta objVentas = new Registrar_Venta();
        contenedor.add(objVentas).setVisible(true);       
    }//GEN-LAST:event_menuVentaActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
       Registrar_Producto obj = null;
        try {
            obj = new Registrar_Producto();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
       contenedor.add(obj).setVisible(true);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
              
        try {                                           
            
            Registrar_Cliente cdb = new Registrar_Cliente();
            cdb.setVisible(true);
            contenedor.add(cdb);  
            
        } catch (SQLException ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
               
        try {
            Registrar_Vendedor cdb = new Registrar_Vendedor();
            cdb.setVisible(true);
            contenedor.add(cdb);
        } catch (SQLException ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void menuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedorActionPerformed
        try {
            // TODO add your handling code here:
            
            Registrar_Proveedor cdb = new Registrar_Proveedor();
            cdb.setVisible(true);
            contenedor.add(cdb);
        } catch (SQLException ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuProveedorActionPerformed

    private void menuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraActionPerformed

        try {
            Registrar_Compra cdb = new Registrar_Compra();
            cdb.setVisible(true);
            contenedor.add(cdb);
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuCompraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       //save lists
  
        
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      FrmRegistrarUsuario objUsuario =  new FrmRegistrarUsuario( null, false);
      objUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Frm_Infromacion obj = new Frm_Infromacion();
        contenedor.add(obj).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuBuscarProvPorMesyAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarProvPorMesyAnioActionPerformed
        Reporte_Proveedor_PorMesyAño obj= new Reporte_Proveedor_PorMesyAño();
        contenedor.add(obj);
        obj.setVisible(true);

    }//GEN-LAST:event_mnuBuscarProvPorMesyAnioActionPerformed

    private void mnuMayorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMayorPrecioActionPerformed
        // TODO add your handling code here:
        Reporte_Producto_MayorPrecio obj= new Reporte_Producto_MayorPrecio();
        contenedor.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuMayorPrecioActionPerformed

    private void mnuPorcentajeClientesActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPorcentajeClientesActivosActionPerformed
        // TODO add your handling code here:
        Reporte_Clientes_Departamento obj= new Reporte_Clientes_Departamento();
        contenedor.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuPorcentajeClientesActivosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Reporte_Producto_EyC obj = new Reporte_Producto_EyC();
        contenedor.add(obj).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Reporte_Vendedor_MayorEdad obj= new Reporte_Vendedor_MayorEdad();
        contenedor.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try {
            frm_Report_Compra comp = new frm_Report_Compra();
            contenedor.add(comp);
            Dimension desktopSize = contenedor.getSize();
            Dimension FrameSize = comp.getSize();
            comp.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            comp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void coincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coincidenciasActionPerformed
        // TODO add your handling code here:
        fafaf objBuscaProductoxCoincidencia = new fafaf();
        contenedor.add(objBuscaProductoxCoincidencia);
        objBuscaProductoxCoincidencia.setVisible(true);
    }//GEN-LAST:event_coincidenciasActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         try {
            frm_Report_Ventas comp = new frm_Report_Ventas();
            contenedor.add(comp);
            Dimension desktopSize = contenedor.getSize();
            Dimension FrameSize = comp.getSize();
            comp.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            comp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed
     
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem coincidencias;
    public static javax.swing.JLabel contenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuVendedor;
    private javax.swing.JMenuItem menuVenta;
    private javax.swing.JMenu menureporte;
    private javax.swing.JMenuItem mnuBuscarProvPorMesyAnio;
    private javax.swing.JMenuItem mnuMayorPrecio;
    private javax.swing.JMenuItem mnuPorcentajeClientesActivos;
    // End of variables declaration//GEN-END:variables
}
