/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.Controller_ubigeo;
import Capa_Logica.Cliente;
import ListasAux.ListaEnlazada;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import utils.Alternos;


/**
 *
 * @author Gianx
 */
public class Reporte_Clientes_Departamento extends javax.swing.JInternalFrame {
    Controller_ubigeo ubi = new Controller_ubigeo();
    
    
    public Reporte_Clientes_Departamento() {
        initComponents();  
        ubi.Sql="SELECT nom_departamento FROM ub_departamento ORDER BY nom_departamento ASC";
        ubi.llenarComboUBIGEO(cbodepa, ubi.Sql,1);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        cbodepa = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGrafico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHombres = new javax.swing.JLabel();
        lblMujeres = new javax.swing.JLabel();
        lblHombresInac = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblMujeresInac = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REPORTE CLIENTE: MOSTRAR LOS CLIENTES EN GRAFICO - COLLAZOS MIO");

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.setForeground(new java.awt.Color(204, 255, 255));

        cbodepa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbodepaItemStateChanged(evt);
            }
        });
        cbodepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodepaActionPerformed(evt);
            }
        });

        jLabel6.setText("Departamento:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CLIENTE CON LA MAYOR COMPRA");

        btnMostrar.setText("BUSCAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MOSTRAR LA CANTIDAD DE CLIENTES POR DEPARTAMENTOS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PORCENTAJES");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Activos");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Inactivos");

        btnGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo-report.png"))); // NOI18N
        btnGrafico.setText("VER GRÁFICO");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jLabel11.setText("Hombres:");

        jLabel12.setText("Mujeres:");

        jLabel13.setText("Hombres:");

        jLabel14.setText("Mujeres:");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iconfinder_new-document-empty-file-sheet_2931173.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("%");

        jLabel3.setText("%");

        jLabel4.setText("%");

        jLabel5.setText("%");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(lblMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(123, 123, 123))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btnGrafico)
                                .addGap(78, 78, 78)
                                .addComponent(btnLimpiar))
                            .addComponent(jLabel7)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(57, 57, 57))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(lblHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGap(156, 156, 156)
                                                .addComponent(lblMujeresInac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addComponent(lblHombresInac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))))))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbodepa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btnMostrar)))))
                .addGap(40, 40, 40))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnMostrar)
                    .addComponent(cbodepa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, 0)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)))
                                    .addComponent(lblHombresInac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMujeres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel3))))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(lblMujeresInac, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(btnGrafico))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbodepaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbodepaItemStateChanged

    }//GEN-LAST:event_cbodepaItemStateChanged

    private void cbodepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodepaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodepaActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
      
      if(cbodepa.getSelectedIndex()!=-1){
        mayorCompra();
        porcentajeActivos();
        porcentajeInactivos();
        }else{
          Alternos.message("No has seleccionado ningun departamento");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        grafico();
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       lblHombres.setText("");
       lblMujeres.setText("");
       
       lblHombresInac.setText("");
       lblMujeresInac.setText("");
      
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    
    public void porcentajeActivos(){
    
     float porcentaje[]=Cliente.porcentajeClientesActivosHyM();
       lblHombres.setText(String.valueOf(porcentaje[0]));
       lblMujeres.setText(String.valueOf(porcentaje[1]));
    }
    public void porcentajeInactivos(){
    
     float porcentaje[]=Cliente.porcentajeClientesInactivosHyM();
       lblHombresInac.setText(String.valueOf(porcentaje[0]));
       lblMujeresInac.setText(String.valueOf(porcentaje[1]));
    }
    public void mayorCompra(){
        
        DefaultTableModel model = new DefaultTableModel(); 
            
         model.addColumn("NUM. DE DOC COMPRA");
         model.addColumn("DNI");
         model.addColumn("NOMBRES");
         model.addColumn("APELLIDOS");
         model.addColumn("EDAD");
         model.addColumn("SEXO");
         model.addColumn("CORREO");
         model.addColumn("CELULAR");
         model.addColumn("FECHA NAC");
         model.addColumn("DIRECCION");
         model.addColumn("DEP");
          
         ListaEnlazada datos = Cliente.clientesMayorCompra(cbodepa.getSelectedItem().toString());
         Object Dato[] = new Object[11];           
         for (int i = 0; i < datos.tamaño(); i++) {
             Cliente cdb = (Cliente)datos.Buscar(i);
             Dato[0]=cdb.getCodVenta();
             Dato[1]=cdb.getDNI();
             Dato[2]=cdb.getNombre();
             Dato[3]=cdb.getApellidos();
             Dato[4]=cdb.getEdad();
             Dato[5]=cdb.getSexo();
             Dato[6]=cdb.getCorreo();
             Dato[7]=cdb.getCelular();
             Dato[8]=cdb.getFnac();
             Dato[9]=cdb.getDireccion();
             Dato[10]=cdb.getDep();
             model.addRow(Dato);
         }
         this.tblDatos.setModel(model);
    
        
    }
    public void grafico(){
            DefaultPieDataset data = new DefaultPieDataset();
            int numCliente[] = Cliente.clientesDepartamento();
            data.setValue("Amazonas",numCliente[0]);
            data.setValue("Ancash",numCliente[1]);
            data.setValue("Apurimac",numCliente[2]);
            data.setValue("Arequipa",numCliente[3]);
            data.setValue("Ayacucho",numCliente[4]);
            data.setValue("Cajamarca",numCliente[5]);
            data.setValue("Callao",numCliente[6]);
            data.setValue("Cusco",numCliente[7]);
            data.setValue("Huancavelica",numCliente[8]);
            data.setValue("Huanuco",numCliente[9]);
            data.setValue("Ica",numCliente[10]);
            data.setValue("Junín",numCliente[11]);
            data.setValue("La Libertad",numCliente[12]);
            data.setValue("Lambayeque",numCliente[13]);
            data.setValue("Lima",numCliente[14]);
            data.setValue("Loreto",numCliente[15]);
            data.setValue("Madre de Dios",numCliente[16]);
            data.setValue("Moquegua",numCliente[17]);
            data.setValue("Pasco",numCliente[18]);
            data.setValue("Piura",numCliente[19]);
            data.setValue("Puno",numCliente[20]);
            data.setValue("San Martín",numCliente[21]);
            data.setValue("Tacna",numCliente[22]);
            data.setValue("Tumbes",numCliente[23]);
            data.setValue("Ucayali",numCliente[24]);

            // Creando el Grafico
            JFreeChart chart = ChartFactory.createPieChart(
                    "GRAFICO DE CANTIDAD DE CLIENTES POR DEPARTAMENTO",
                    data,
                    true,
                    true,
                    false);

            // Mostrar Grafico
            ChartFrame frame = new ChartFrame("GRAFICO DE CANTIDAD", chart);
            frame.pack();
            frame.setVisible(true);
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cbodepa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHombres;
    private javax.swing.JLabel lblHombresInac;
    private javax.swing.JLabel lblMujeres;
    private javax.swing.JLabel lblMujeresInac;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
