/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Capa_Cliente;

import Capa_Datos.Lista_Productos;
import Capa_Logica.Coincidencia;
import Capa_Logica.DetalleVenta;
import Capa_Logica.Producto;
import ListasAux.ListaEnlazada;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import utils.Alternos;

/**
 *
 * @author Gianx
 */
public class Reporte_BuscaProductoxCoincidencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reporte_BuscaProductoxCoincidencia
     */
        ListaEnlazada lista =  null;
    public Reporte_BuscaProductoxCoincidencia() {
        initComponents();
     
        
    }

 
   private DefaultTableModel renderTable(ListaEnlazada lista){
            DefaultTableModel modelo = new DefaultTableModel();
        ListaEnlazada LP;

        modelo.addColumn("ID Prod.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        modelo.addColumn("Categoria");
        modelo.addColumn("T. Unidad");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");

        Object datos[] = new Object[7];

        LP = lista;

        for (int i = 0; i < LP.tamaño(); i++) {
            Producto objCliente = (Producto) LP.Buscar(i);
            datos[0] = objCliente.getCodProducto();
            datos[1] = objCliente.getNombre();
            datos[2] = objCliente.getEstado();
            datos[3] = objCliente.getCategoria();
            datos[4] = objCliente.getUnidad();
            datos[5] = objCliente.getCantidad();
            datos[6] = objCliente.getPrecio();

            modelo.addRow(datos);
        } 
       return modelo;
   }
   
      private DefaultTableModel renderTableCoincidencia(ListaEnlazada lista){
            DefaultTableModel modelo = new DefaultTableModel();
        ListaEnlazada LP;

        modelo.addColumn("fecha");
        modelo.addColumn("mes");
        modelo.addColumn("monto");
 
       Object datos[] = new Object[3];

        LP = lista;

        for (int i = 0; i < LP.tamaño(); i++) {
            Coincidencia objCliente = (Coincidencia) LP.Buscar(i);
            datos[0] = objCliente.fecha;
            datos[1] = objCliente.getMes();         
            datos[2]  = objCliente.monto;
            modelo.addRow(datos);
        } 
       return modelo;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNice1 = new org.edisoncor.gui.button.ButtonNice();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateStart = new com.toedter.calendar.JDateChooser();
        dateEnd = new com.toedter.calendar.JDateChooser();
        buttonRect1 = new org.edisoncor.gui.button.ButtonRect();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        buttonNice1.setText("buttonNice1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        buttonRect1.setText("buscar");
        buttonRect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRect1ActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDatos);

        jButton1.setText("grafico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(buttonRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(buttonRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRect1ActionPerformed
        Date  comienzo =  dateStart.getDateEditor().getDate();
        Date  fin =  dateEnd.getDateEditor().getDate();
        
        
     lista =   DetalleVenta.buscarVentar(comienzo, fin);
        tblDatos.setModel(renderTableCoincidencia(lista));
       
    }//GEN-LAST:event_buttonRect1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(lista == null){
            Alternos.message("No se ha generado el reporte");
         return;
        }
        renderGrafico(lista);
    }//GEN-LAST:event_jButton1ActionPerformed
     void renderGrafico(ListaEnlazada lista){
               DefaultPieDataset data = new DefaultPieDataset();
          for (int i = 0; i < lista.tamaño(); i++) {
             Coincidencia objCoincidencia = (Coincidencia) lista.Buscar(i);
             data.setValue(objCoincidencia.getMes(), objCoincidencia.monto);
         }
            JFreeChart chart = ChartFactory.createPieChart(
                    "grafico",data, true, true, false);

            // Mostrar Grafico
            ChartFrame frame = new ChartFrame("GRAFICO", chart);
            frame.pack();
            frame.setVisible(true);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice buttonNice1;
    private org.edisoncor.gui.button.ButtonRect buttonRect1;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
